
/* Auto-generated by genmsg_cpp for file /home/viki/groovy_workspace/ICT_Viper/srv/CvService.srv */



#ifndef ICT_VIPER_SERVICE_CVSERVICE_H
#define ICT_VIPER_SERVICE_CVSERVICE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace ICT_Viper
{
template <class ContainerAllocator>
struct CvServiceRequest_ {
  typedef CvServiceRequest_<ContainerAllocator> Type;

  CvServiceRequest_()
  : A(0)
  {
  }

  CvServiceRequest_(const ContainerAllocator& _alloc)
  : A(0)
  {
  }

  typedef int32_t _A_type;
  int32_t A;


  typedef boost::shared_ptr< ::ICT_Viper::CvServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ICT_Viper::CvServiceRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CvServiceRequest
typedef  ::ICT_Viper::CvServiceRequest_<std::allocator<void> > CvServiceRequest;

typedef boost::shared_ptr< ::ICT_Viper::CvServiceRequest> CvServiceRequestPtr;
typedef boost::shared_ptr< ::ICT_Viper::CvServiceRequest const> CvServiceRequestConstPtr;


template <class ContainerAllocator>
struct CvServiceResponse_ {
  typedef CvServiceResponse_<ContainerAllocator> Type;

  CvServiceResponse_()
  : Coords(0)
  {
  }

  CvServiceResponse_(const ContainerAllocator& _alloc)
  : Coords(0)
  {
  }

  typedef int32_t _Coords_type;
  int32_t Coords;


  typedef boost::shared_ptr< ::ICT_Viper::CvServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ICT_Viper::CvServiceResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CvServiceResponse
typedef  ::ICT_Viper::CvServiceResponse_<std::allocator<void> > CvServiceResponse;

typedef boost::shared_ptr< ::ICT_Viper::CvServiceResponse> CvServiceResponsePtr;
typedef boost::shared_ptr< ::ICT_Viper::CvServiceResponse const> CvServiceResponseConstPtr;

struct CvService
{

typedef CvServiceRequest Request;
typedef CvServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct CvService
} // namespace ICT_Viper

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ICT_Viper::CvServiceRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ICT_Viper::CvServiceRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ICT_Viper::CvServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2f74de675724ea76427c4018b917fc67";
  }

  static const char* value(const  ::ICT_Viper::CvServiceRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2f74de675724ea76ULL;
  static const uint64_t static_value2 = 0x427c4018b917fc67ULL;
};

template<class ContainerAllocator>
struct DataType< ::ICT_Viper::CvServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ICT_Viper/CvServiceRequest";
  }

  static const char* value(const  ::ICT_Viper::CvServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ICT_Viper::CvServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 A\n\
\n\
";
  }

  static const char* value(const  ::ICT_Viper::CvServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ICT_Viper::CvServiceRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ICT_Viper::CvServiceResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ICT_Viper::CvServiceResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ICT_Viper::CvServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "50c4f9766cb0bd7ba2c25a50239aa53e";
  }

  static const char* value(const  ::ICT_Viper::CvServiceResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x50c4f9766cb0bd7bULL;
  static const uint64_t static_value2 = 0xa2c25a50239aa53eULL;
};

template<class ContainerAllocator>
struct DataType< ::ICT_Viper::CvServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ICT_Viper/CvServiceResponse";
  }

  static const char* value(const  ::ICT_Viper::CvServiceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ICT_Viper::CvServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 Coords\n\
\n\
\n\
";
  }

  static const char* value(const  ::ICT_Viper::CvServiceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ICT_Viper::CvServiceResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ICT_Viper::CvServiceRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.A);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CvServiceRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ICT_Viper::CvServiceResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Coords);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CvServiceResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<ICT_Viper::CvService> {
  static const char* value() 
  {
    return "2c7788a4f8698f5dedc687abaee2c458";
  }

  static const char* value(const ICT_Viper::CvService&) { return value(); } 
};

template<>
struct DataType<ICT_Viper::CvService> {
  static const char* value() 
  {
    return "ICT_Viper/CvService";
  }

  static const char* value(const ICT_Viper::CvService&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<ICT_Viper::CvServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2c7788a4f8698f5dedc687abaee2c458";
  }

  static const char* value(const ICT_Viper::CvServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<ICT_Viper::CvServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ICT_Viper/CvService";
  }

  static const char* value(const ICT_Viper::CvServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<ICT_Viper::CvServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2c7788a4f8698f5dedc687abaee2c458";
  }

  static const char* value(const ICT_Viper::CvServiceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<ICT_Viper::CvServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ICT_Viper/CvService";
  }

  static const char* value(const ICT_Viper::CvServiceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ICT_VIPER_SERVICE_CVSERVICE_H

